- hosts: localhost
  connection: local
  tasks:
    - name: k8s Discovery
      ansible.builtin.include_role:
        name: k8s-discovery
    - name: debug
      ansible.builtin.debug:
        msg: "{{ groups  }}"

- hosts: eap
  tasks:
    - name: Print OS Version
      ansible.builtin.debug:
        msg: "{{ lookup('file', '/etc/redhat-release') }}  }}"